schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "JchEnvironmentInput"
  types:
    JchEnvironmentInput:
      type: object
      description: "Input properties for my environment"
      properties:
        codebuild_vpc_id:
          type: string
        codebuild_subnets:
          type: array
          items:
            type: string
        codebuild_security_groups:
          type: array
          items:
            type: string
        vpc_cidr:
          type: string
          description: "The CIDR range for your VPC"
          default: 10.0.0.0/16
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))
        public_subnet_one_cidr:
          type: string
          description: "The CIDR range for public subnet one"
          default: 10.0.0.0/18
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))
        public_subnet_two_cidr:
          type: string
          description: "The CIDR range for public subnet two"
          default: 10.0.64.0/18
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))
        private_subnet_one_cidr:
          type: string
          description: "The CIDR range for private subnet one"
          default: 10.0.128.0/18
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))
        private_subnet_two_cidr:
          type: string
          description: "The CIDR range for private subnet two"
          default: 10.0.192.0/18
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))
        golden_ami_param_name:
          type: string
          description: "The name of a golden AMI SSM parameter"
          default: cis/goldenami
          pattern: ^([a-zA-Z0-9]+\/)*[a-zA-Z0-9]+$
        my_sample_input:
          type: string
          description: "Sample input"
          default: sampleInput
          pattern: ^[a-zA-Z]+$
      required:
        - vpc_cidr
        - my_sample_input
